### ISSUE TITLE
link to old archived site gone

### ISSUE THREAD

**Issue by debpaul** [sfg-taxonpages/isoptera#1]
@hhopkins77 did you really want to remove the link to the old website?

I see that [http://{{app:focal_taxon}}.archive.speciesfile.org](https://%7B%7Bapp:focal_taxon%7D%7D.archive.speciesfile.org) is gone?

**Comment by LocoDelAssembly** [comment]
This is not a legacy SF being migrated to TW, it is a completely new SF.

**Comment by debpaul** [comment]
> This is not a legacy SF being migrated to TW, it is a completely new SF.

Thanks @LocoDelAssembly I didn't realize that. So we can close this and "won't fix" because it's not broken :-)
