### ISSUE TITLE
Asserted distribution & Georeference - source database?

### ISSUE THREAD

**Issue by AlesBucek** [sfg-taxonpages/isoptera#5]
Hi!
What is the source of geographical distribution data visualized in the map? 
I started to search for the source as I thought that e.g. Macrotermitinae in Europe (https://isoptera.speciesfile.org/otus/656672/overview) is an error until I realized it is a fossil occurence. 
GBIF indeed has this fossil occurence record but in addition it has an occurence of Gnathotermes (old synonym of Macrotermes) in USA (https://www.gbif.org/occurrence/map?taxon_key=4803134). 
This is very likely incorrect identification of fossil in the original article (no other extant or fossil Macrotermes in Americas) so I'm wondering if the GBIF occurences are being manually or automatically revised before incorporating into taxonworks or whether the occurence source database is different than GBIF? 
Thanks! Ales Bucek

**Comment by mjy** [comment]
@AlesBucek Welcome in.  @hhopkins77  our active lead here, and will provide some history I think.  

I'll point out 2 things in the screenshot below you'll see a triangle, clicking on this gives a breakdown of the "classes" of data behind the map, sensu TaxonWorks, and the DwC link provides a snapshot of all "occurrnce" data (specimen and literature, the latter we call AssertedDistributiions). 

<img width="911" alt="Screenshot 2024-10-11 at 9 19 25 AM" src="https://github.com/user-attachments/assets/dea8ac61-2052-414c-ae73-f8c92d80e36f">

IIRC there is some recent interest in growing Isoptera resources, we'd be happy to demo the internals, see our Wednesday events schedule in particular- http://speciesfilegroup.org/events, and of course it takes a full community to curate these resources, contributions at all levels (like this issue) are very welcome.  We have an excellent and evolving DwC importer, it might be that we can start to have curators sync GBIF originating data.

**Comment by hhopkins77** [comment]
Hi Ales,

Distribution data for Isoptera SF is from the Treatise by Krishna et al., 2013, and from distributions published in the scientific literature since then.

As Matt mentioned we are always looking for additional workers who might want to tackle additional data sources. Our Wednesday meetings can be a great way to get started, but I can also meet with interested parties at other times if Wednesdays don't work.

--Heidi

**Comment by AlesBucek** [comment]
@mjy, @hhopkins77 : thanks! The DwC table provides all the answers concerning the occurence data source - thx! Just a note: the downloaded file is called *.csv while it seems to be a tab-separated table instead. 
I'll keep in touch.
Ales
